# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Cache Bundler
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundle-
    - name: Install Bundle dependencies
      run: bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs 4 --retry 3

#     - name: Run RSpec
#       run: bundle exec rails parallel:spec[4]

#     - name: Upload coverage
#       uses: actions/upload-artifact@v1
#       with:
#         name: coverage
#         path: coverage

  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Cache Bundler
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundle-
    - name: Install Bundle dependencies
      run: bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs 4 --retry 3

    - name: Run Rubocop
      run: bundle exec rubocop -P --config .rubocop.yml
